// Готовая колода: 100 самых ходовых разговорных фраз, которые реально используют
// в повседневном общении в США — приветствия, вежливые формулы, согласие/несогласие,
// реакции, просьбы, телефон/переписка, кафе и магазины, идиомы, рабочие фразы
export const TOP_100_PHRASES = [
  // Приветствия и прощания
  { word: 'Hi there!', translation: 'Привет!', example: "Hi there! Haven't seen you in a while." },
  { word: "What's up?", translation: 'Привет! Как дела? / Что нового?', example: "Hey, what's up? Wanna grab lunch?" },
  { word: "How's it going?", translation: 'Как дела? Как оно?', example: "How's it going, man? Long time!" },
  { word: 'How have you been?', translation: 'Как ты поживал(а)?', example: 'Hey! How have you been since college?' },
  { word: 'Long time no see', translation: 'Давно не виделись', example: 'Long time no see! You look great.' },
  { word: 'Nice to meet you', translation: 'Приятно познакомиться', example: "Nice to meet you, I've heard a lot about you." },
  { word: 'Take care', translation: 'Береги себя (при прощании)', example: 'Alright, I gotta go. Take care!' },
  { word: 'See you around', translation: 'Увидимся (как-нибудь)', example: 'See you around, maybe next week.' },
  { word: 'Catch you later', translation: 'Увидимся позже', example: "I'm heading out, catch you later." },
  { word: 'Have a good one', translation: 'Хорошего дня (неформальное прощание)', example: 'Thanks, you too — have a good one!' },

  // Вежливые формулы
  { word: 'Thanks a lot', translation: 'Большое спасибо', example: 'Thanks a lot for helping me move.' },
  { word: "You're welcome", translation: 'Пожалуйста (в ответ на спасибо)', example: 'Thank you! — You’re welcome.' },
  { word: 'No problem', translation: 'Без проблем / Не за что', example: 'Can you hold the door? — No problem.' },
  { word: 'Excuse me', translation: 'Извините (привлечь внимание, протиснуться)', example: 'Excuse me, do you know where the restroom is?' },
  { word: "I'm sorry", translation: 'Извините / Прошу прощения', example: "I'm sorry, I didn't mean to interrupt." },
  { word: 'My pleasure', translation: 'Мне только в радость / Рад помочь', example: 'Thanks for the ride! — My pleasure.' },
  { word: 'After you', translation: 'После вас (пропустить вперёд)', example: 'After you — go ahead through the door.' },
  { word: 'Bless you', translation: 'Будь здоров(а) (после чихания)', example: 'Achoo! — Bless you!' },
  { word: 'Sorry about that', translation: 'Извини за это / Прости', example: 'Sorry about that, I totally forgot to call.' },
  { word: "Don't mention it", translation: 'Не стоит благодарности', example: "Thanks for everything. — Don't mention it." },

  // Согласие и несогласие
  { word: 'Sounds good', translation: 'Звучит хорошо / Годится', example: 'Let’s meet at 6? — Sounds good.' },
  { word: "I'm in", translation: 'Я в деле', example: "We're going hiking Saturday. — I'm in!" },
  { word: 'Count me in', translation: 'Учти и меня', example: 'There’s a game night Friday. — Count me in!' },
  { word: 'No way', translation: 'Ни за что / Да ладно', example: 'No way, he actually said that?' },
  { word: 'I doubt it', translation: 'Сомневаюсь', example: 'Will it rain tomorrow? — I doubt it.' },
  { word: 'Fair enough', translation: 'Справедливо, ладно', example: "I'd rather stay home tonight. — Fair enough." },
  { word: 'That makes sense', translation: 'Это логично', example: 'Oh, that makes sense now, thanks for explaining.' },
  { word: 'I guess so', translation: 'Наверное, пожалуй', example: 'Do you want to come? — I guess so.' },
  { word: 'Not really', translation: 'Не особо / Не совсем', example: 'Are you hungry? — Not really.' },
  { word: 'Absolutely', translation: 'Безусловно / Точно', example: 'Can you help me tomorrow? — Absolutely.' },

  // Реакции
  { word: 'No kidding', translation: 'Серьёзно? / Да ладно', example: 'He quit his job. — No kidding!' },
  { word: 'Are you kidding me?', translation: 'Ты шутишь?', example: 'We won the lottery! — Are you kidding me?' },
  { word: "That's crazy", translation: 'Это безумие, с ума сойти', example: 'She ran a marathon in under three hours. That’s crazy.' },
  { word: "I can't believe it", translation: 'Не могу поверить', example: "I can't believe it's already December." },
  { word: 'Oh my god', translation: 'О боже', example: 'Oh my god, look at that view!' },
  { word: "You've got to be kidding", translation: 'Да ладно, не может быть', example: 'It costs how much? You’ve got to be kidding.' },
  { word: 'Get out of here', translation: 'Да ладно! Не может быть! (разг.)', example: 'You got the job? Get out of here, congrats!' },
  { word: 'What a relief', translation: 'Какое облегчение', example: 'The test results were negative. What a relief.' },
  { word: "That's a shame", translation: 'Как жаль / Обидно', example: 'He couldn’t make it to the party. That’s a shame.' },
  { word: 'Good for you', translation: 'Молодец! Рад за тебя', example: 'I finally finished my degree. — Good for you!' },

  // Слова-паразиты и связки в разговоре
  { word: 'I mean', translation: 'Я имею в виду / То есть', example: "I mean, it's not perfect, but it works." },
  { word: 'You know what I mean?', translation: 'Понимаешь, о чём я?', example: 'It’s just weird being back here, you know what I mean?' },
  { word: 'Kind of', translation: 'Вроде как / Типа того', example: 'Are you tired? — Kind of, yeah.' },
  { word: 'Sort of', translation: 'Вроде того / Отчасти', example: 'Do you understand the assignment? — Sort of.' },
  { word: 'No worries', translation: 'Всё нормально, не переживай', example: 'Sorry I’m late! — No worries at all.' },
  { word: 'It is what it is', translation: 'Что есть, то есть', example: 'We can’t change the schedule now. It is what it is.' },
  { word: 'Anyway', translation: 'В общем, так или иначе', example: 'Anyway, let’s get back to the main topic.' },
  { word: 'By the way', translation: 'Кстати', example: 'By the way, did you finish the report?' },
  { word: 'Speaking of which', translation: 'Кстати говоря, к слову', example: 'Speaking of which, I saw Mark yesterday.' },
  { word: 'Long story short', translation: 'Короче говоря', example: 'Long story short, we missed the flight.' },

  // Просьбы и предложения
  { word: 'Can I get...?', translation: 'Можно мне...? (в кафе, магазине)', example: 'Can I get a coffee to go, please?' },
  { word: 'Would you mind...?', translation: 'Не могли бы вы...? (вежливая просьба)', example: 'Would you mind closing the window?' },
  { word: 'Do you mind if I...?', translation: 'Ты не против, если я...?', example: 'Do you mind if I sit here?' },
  { word: 'Hold on a sec', translation: 'Секунду, подожди чуть-чуть', example: 'Hold on a sec, I need to grab my phone.' },
  { word: 'Give me a second', translation: 'Дай мне секунду', example: "Give me a second, I'll be right there." },
  { word: 'Hang on', translation: 'Погоди / Секунду', example: 'Hang on, let me check my calendar.' },
  { word: 'Let me think about it', translation: 'Дай подумать', example: "Let me think about it and I'll get back to you." },
  { word: "I'll get back to you", translation: 'Я отвечу тебе позже', example: "I'm not sure yet — I'll get back to you tomorrow." },
  { word: 'Can we reschedule?', translation: 'Можем перенести (встречу)?', example: 'Something came up, can we reschedule the meeting?' },
  { word: 'That works for me', translation: 'Мне подходит', example: 'Let’s meet at noon. — That works for me.' },

  // Телефон и переписка
  { word: 'Can you hear me?', translation: 'Ты меня слышишь?', example: "Hello? Can you hear me? The line's bad." },
  { word: "You're breaking up", translation: 'Связь прерывается', example: "Sorry, you're breaking up, can you say that again?" },
  { word: "I'll call you back", translation: 'Я тебе перезвоню', example: "I'm in a meeting, I'll call you back in an hour." },
  { word: 'Text me', translation: 'Напиши мне (смс)', example: 'Text me when you get home safe.' },
  { word: 'Let me know', translation: 'Дай знать', example: 'Let me know if the time works for you.' },
  { word: "I'll keep you posted", translation: 'Буду держать в курсе', example: "No news yet, but I'll keep you posted." },
  { word: 'Talk to you later', translation: 'Поговорим позже', example: 'Gotta run, talk to you later!' },
  { word: 'Give me a call', translation: 'Позвони мне', example: "Give me a call when you're free." },
  { word: 'Pick up the phone', translation: 'Возьми трубку', example: "I tried calling you — why didn't you pick up the phone?" },
  { word: 'Leave a message', translation: 'Оставь сообщение', example: "He's not available, please leave a message after the beep." },

  // Кафе и магазины
  { word: 'Can I get the check, please?', translation: 'Можно счёт, пожалуйста?', example: "We're all set — can I get the check, please?" },
  { word: 'For here or to go?', translation: 'Здесь или с собой?', example: 'For here or to go? — To go, please.' },
  { word: "I'm just browsing", translation: 'Я просто смотрю', example: "Can I help you find something? — I'm just browsing, thanks." },
  { word: 'Do you take cards?', translation: 'Вы принимаете карты?', example: 'Do you take cards, or cash only?' },
  { word: 'Can I get a refund?', translation: 'Могу получить возврат денег?', example: 'This doesn’t fit — can I get a refund?' },
  { word: "It's on me", translation: 'Я угощаю', example: "Don't worry about the bill, it's on me." },
  { word: 'On the house', translation: 'За счёт заведения', example: "Enjoy the dessert — it's on the house tonight." },
  { word: 'Keep the change', translation: 'Оставьте сдачу себе', example: "Here's twenty bucks, keep the change." },
  { word: "I'll have the same", translation: 'Мне то же самое', example: "I'll have the same as him, thanks." },
  { word: 'Check, please', translation: 'Счёт, пожалуйста', example: "We're done eating — check, please!" },

  // Идиомы
  { word: 'Break a leg', translation: 'Ни пуха ни пера (пожелание удачи)', example: "You've got the audition today — break a leg!" },
  { word: 'Piece of cake', translation: 'Проще простого', example: 'Don’t worry, the test was a piece of cake.' },
  { word: 'Hang in there', translation: 'Держись', example: "I know it's tough right now — just hang in there." },
  { word: "Let's call it a day", translation: 'На сегодня хватит', example: "We've done a lot already — let's call it a day." },
  { word: 'My bad', translation: 'Моя вина, извини', example: 'I forgot to send the email — my bad.' },
  { word: 'Give it a shot', translation: 'Попробовать, рискнуть', example: "You might not win, but give it a shot anyway." },
  { word: 'Up to you', translation: 'Тебе решать', example: 'Pizza or sushi tonight? — Up to you.' },
  { word: 'No biggie', translation: 'Пустяки, не проблема', example: "You broke a glass? No biggie, don't worry." },
  { word: 'Once in a blue moon', translation: 'Очень редко', example: 'We only see each other once in a blue moon.' },
  { word: 'Cut it out', translation: 'Хватит, прекрати', example: 'Stop tickling me, cut it out!' },

  // Работа и повседневные мнения
  { word: "Let's touch base", translation: 'Давай созвонимся/свяжемся (обсудить дела)', example: "Let's touch base next week about the project." },
  { word: 'Keep me in the loop', translation: 'Держи меня в курсе', example: 'Whatever happens with the deal, keep me in the loop.' },
  { word: 'It depends', translation: 'Зависит от обстоятельств', example: 'Are you coming to the party? — It depends on work.' },
  { word: "I'm not sure", translation: 'Я не уверен(а)', example: "I'm not sure if that's the right decision." },
  { word: "Let's play it by ear", translation: 'Решим по ситуации', example: "We don't have a fixed plan, let's just play it by ear." },
  { word: "That's a good point", translation: 'Это хорошая мысль/довод', example: "That's a good point, I hadn't thought of that." },
  { word: 'On second thought', translation: 'Если подумать ещё раз', example: 'On second thought, let’s take the highway instead.' },
  { word: 'Deal', translation: 'Договорились', example: "I'll cook if you clean up. — Deal." },
  { word: 'Never mind', translation: 'Забудь, неважно', example: "Never mind, it wasn't that important anyway." },
  { word: "That's the spirit", translation: 'Вот это настрой!', example: "You'll nail the interview — that's the spirit!" },
]
