// Готовая колода: 1000 самых частотных английских слов с переводом.
// Список включает служебные слова (местоимения, предлоги, союзы), базовую
// бытовую лексику по темам (дом, еда, работа, природа, эмоции и т.д.)
// и самые употребимые глаголы и прилагательные.
export const TOP_1000_WORDS = [
  { word: "I", translation: "я" },
  { word: "you", translation: "ты, вы" },
  { word: "he", translation: "он" },
  { word: "she", translation: "она" },
  { word: "it", translation: "оно, это" },
  { word: "we", translation: "мы" },
  { word: "they", translation: "они" },
  { word: "me", translation: "мне, меня" },
  { word: "him", translation: "ему, его" },
  { word: "her", translation: "ей, её" },
  { word: "us", translation: "нам, нас" },
  { word: "them", translation: "им, их" },
  { word: "my", translation: "мой" },
  { word: "your", translation: "твой, ваш" },
  { word: "his", translation: "его" },
  { word: "its", translation: "его, её (о предмете)" },
  { word: "our", translation: "наш" },
  { word: "their", translation: "их" },
  { word: "mine", translation: "мой (чей? — мой)" },
  { word: "yours", translation: "твой (чей? — твой)" },
  { word: "ours", translation: "наш (чей? — наш)" },
  { word: "theirs", translation: "их (чей? — их)" },
  { word: "myself", translation: "себя, сам" },
  { word: "yourself", translation: "себя, сам (ты)" },
  { word: "himself", translation: "себя, сам (он)" },
  { word: "herself", translation: "себя, сама (она)" },
  { word: "itself", translation: "само, сама по себе" },
  { word: "ourselves", translation: "себя, сами (мы)" },
  { word: "yourselves", translation: "себя, сами (вы)" },
  { word: "themselves", translation: "себя, сами (они)" },
  { word: "this", translation: "этот, это" },
  { word: "that", translation: "тот, то" },
  { word: "these", translation: "эти" },
  { word: "those", translation: "те" },
  { word: "who", translation: "кто" },
  { word: "whom", translation: "кого, кому" },
  { word: "whose", translation: "чей" },
  { word: "which", translation: "который, какой" },
  { word: "what", translation: "что" },
  { word: "someone", translation: "кто-то" },
  { word: "somebody", translation: "кто-то" },
  { word: "something", translation: "что-то" },
  { word: "anyone", translation: "кто-нибудь" },
  { word: "anybody", translation: "кто-нибудь" },
  { word: "anything", translation: "что-нибудь" },
  { word: "everyone", translation: "каждый, все" },
  { word: "everybody", translation: "все" },
  { word: "everything", translation: "всё" },
  { word: "nobody", translation: "никто" },
  { word: "nothing", translation: "ничто" },
  { word: "none", translation: "никакой, ни один" },
  { word: "all", translation: "все, всё" },
  { word: "both", translation: "оба" },
  { word: "each", translation: "каждый" },
  { word: "either", translation: "любой из двух" },
  { word: "neither", translation: "ни тот ни другой" },
  { word: "other", translation: "другой" },
  { word: "another", translation: "ещё один, другой" },
  { word: "one", translation: "один; кто-то (безличное)" },
  { word: "some", translation: "несколько, некоторые" },
  { word: "any", translation: "любой, какой-нибудь" },
  { word: "many", translation: "много" },
  { word: "much", translation: "много" },
  { word: "few", translation: "мало, немного" },
  { word: "little", translation: "мало, немного" },
  { word: "several", translation: "несколько" },
  { word: "most", translation: "большинство" },
  { word: "yes", translation: "да" },
  { word: "no", translation: "нет" },
  { word: "please", translation: "пожалуйста" },
  { word: "thanks", translation: "спасибо" },
  { word: "sorry", translation: "извините, простите" },
  { word: "hello", translation: "привет, здравствуйте" },
  { word: "hi", translation: "привет" },
  { word: "goodbye", translation: "до свидания" },
  { word: "bye", translation: "пока" },
  { word: "welcome", translation: "добро пожаловать" },
  { word: "okay", translation: "хорошо, ладно" },
  { word: "excuse", translation: "извинять; предлог (извините)" },
  { word: "a", translation: "неопределённый артикль" },
  { word: "an", translation: "неопределённый артикль (перед гласной)" },
  { word: "the", translation: "определённый артикль" },
  { word: "and", translation: "и" },
  { word: "but", translation: "но" },
  { word: "or", translation: "или" },
  { word: "so", translation: "так что, поэтому" },
  { word: "because", translation: "потому что" },
  { word: "although", translation: "хотя" },
  { word: "though", translation: "хотя, всё же" },
  { word: "while", translation: "пока, в то время как" },
  { word: "if", translation: "если" },
  { word: "unless", translation: "если не" },
  { word: "until", translation: "пока не, до тех пор" },
  { word: "since", translation: "с тех пор как, так как" },
  { word: "whether", translation: "ли (союз)" },
  { word: "nor", translation: "и не, тоже не" },
  { word: "yet", translation: "всё же, ещё" },
  { word: "than", translation: "чем" },
  { word: "in", translation: "в" },
  { word: "on", translation: "на" },
  { word: "at", translation: "у, в, на (о времени/месте)" },
  { word: "by", translation: "у, около, посредством" },
  { word: "for", translation: "для, за" },
  { word: "with", translation: "с" },
  { word: "without", translation: "без" },
  { word: "about", translation: "о, об, около" },
  { word: "against", translation: "против" },
  { word: "between", translation: "между" },
  { word: "into", translation: "в, внутрь" },
  { word: "through", translation: "через, сквозь" },
  { word: "during", translation: "во время" },
  { word: "before", translation: "до, перед" },
  { word: "after", translation: "после" },
  { word: "above", translation: "над, выше" },
  { word: "below", translation: "под, ниже" },
  { word: "under", translation: "под" },
  { word: "over", translation: "над, свыше" },
  { word: "up", translation: "вверх" },
  { word: "down", translation: "вниз" },
  { word: "out", translation: "наружу, вне" },
  { word: "off", translation: "прочь, выключено" },
  { word: "from", translation: "от, из" },
  { word: "to", translation: "к, до" },
  { word: "of", translation: "из, от (принадлежность)" },
  { word: "near", translation: "около, рядом" },
  { word: "behind", translation: "позади" },
  { word: "beside", translation: "рядом с" },
  { word: "among", translation: "среди" },
  { word: "along", translation: "вдоль" },
  { word: "across", translation: "через, поперёк" },
  { word: "around", translation: "вокруг" },
  { word: "within", translation: "внутри, в пределах" },
  { word: "towards", translation: "по направлению к" },
  { word: "upon", translation: "на, по" },
  { word: "inside", translation: "внутри" },
  { word: "outside", translation: "снаружи" },
  { word: "beyond", translation: "за пределами" },
  { word: "be", translation: "быть" },
  { word: "am", translation: "есть (я есть)" },
  { word: "is", translation: "есть (он/она/оно есть)" },
  { word: "are", translation: "есть (мы/вы/они есть)" },
  { word: "was", translation: "был, была, было" },
  { word: "were", translation: "были" },
  { word: "been", translation: "был (причастие)" },
  { word: "being", translation: "being, будучи" },
  { word: "have", translation: "иметь" },
  { word: "has", translation: "имеет" },
  { word: "had", translation: "имел" },
  { word: "having", translation: "имея" },
  { word: "do", translation: "делать" },
  { word: "does", translation: "делает" },
  { word: "did", translation: "делал" },
  { word: "will", translation: "буду, будет (будущее время)" },
  { word: "would", translation: "бы, стал бы" },
  { word: "shall", translation: "должен буду" },
  { word: "should", translation: "следует, должен" },
  { word: "can", translation: "мочь, уметь" },
  { word: "could", translation: "мог бы" },
  { word: "may", translation: "может (разрешение/вероятность)" },
  { word: "might", translation: "мог бы (вероятность)" },
  { word: "must", translation: "должен" },
  { word: "ought", translation: "следовало бы" },
  { word: "when", translation: "когда" },
  { word: "where", translation: "где, куда" },
  { word: "why", translation: "почему" },
  { word: "how", translation: "как" },
  { word: "two", translation: "два" },
  { word: "three", translation: "три" },
  { word: "four", translation: "четыре" },
  { word: "five", translation: "пять" },
  { word: "six", translation: "шесть" },
  { word: "seven", translation: "семь" },
  { word: "eight", translation: "восемь" },
  { word: "nine", translation: "девять" },
  { word: "ten", translation: "десять" },
  { word: "eleven", translation: "одиннадцать" },
  { word: "twelve", translation: "двенадцать" },
  { word: "thirteen", translation: "тринадцать" },
  { word: "fourteen", translation: "четырнадцать" },
  { word: "fifteen", translation: "пятнадцать" },
  { word: "sixteen", translation: "шестнадцать" },
  { word: "seventeen", translation: "семнадцать" },
  { word: "eighteen", translation: "восемнадцать" },
  { word: "nineteen", translation: "девятнадцать" },
  { word: "twenty", translation: "двадцать" },
  { word: "thirty", translation: "тридцать" },
  { word: "forty", translation: "сорок" },
  { word: "fifty", translation: "пятьдесят" },
  { word: "sixty", translation: "шестьдесят" },
  { word: "seventy", translation: "семьдесят" },
  { word: "eighty", translation: "восемьдесят" },
  { word: "ninety", translation: "девяносто" },
  { word: "hundred", translation: "сто" },
  { word: "thousand", translation: "тысяча" },
  { word: "million", translation: "миллион" },
  { word: "billion", translation: "миллиард" },
  { word: "zero", translation: "ноль" },
  { word: "first", translation: "первый" },
  { word: "second", translation: "второй" },
  { word: "third", translation: "третий" },
  { word: "fourth", translation: "четвёртый" },
  { word: "fifth", translation: "пятый" },
  { word: "sixth", translation: "шестой" },
  { word: "seventh", translation: "седьмой" },
  { word: "eighth", translation: "восьмой" },
  { word: "ninth", translation: "девятый" },
  { word: "tenth", translation: "десятый" },
  { word: "last", translation: "последний" },
  { word: "next", translation: "следующий" },
  { word: "time", translation: "время" },
  { word: "day", translation: "день" },
  { word: "night", translation: "ночь" },
  { word: "morning", translation: "утро" },
  { word: "afternoon", translation: "день (после полудня)" },
  { word: "evening", translation: "вечер" },
  { word: "week", translation: "неделя" },
  { word: "month", translation: "месяц" },
  { word: "year", translation: "год" },
  { word: "hour", translation: "час" },
  { word: "minute", translation: "минута" },
  { word: "moment", translation: "момент" },
  { word: "today", translation: "сегодня" },
  { word: "tomorrow", translation: "завтра" },
  { word: "yesterday", translation: "вчера" },
  { word: "now", translation: "сейчас" },
  { word: "then", translation: "тогда, затем" },
  { word: "soon", translation: "скоро" },
  { word: "later", translation: "позже" },
  { word: "early", translation: "рано" },
  { word: "late", translation: "поздно" },
  { word: "always", translation: "всегда" },
  { word: "never", translation: "никогда" },
  { word: "often", translation: "часто" },
  { word: "sometimes", translation: "иногда" },
  { word: "usually", translation: "обычно" },
  { word: "already", translation: "уже" },
  { word: "still", translation: "всё ещё" },
  { word: "again", translation: "снова" },
  { word: "once", translation: "однажды, один раз" },
  { word: "twice", translation: "дважды" },
  { word: "weekend", translation: "выходные" },
  { word: "holiday", translation: "праздник, отпуск" },
  { word: "birthday", translation: "день рождения" },
  { word: "season", translation: "сезон, время года" },
  { word: "spring", translation: "весна" },
  { word: "summer", translation: "лето" },
  { word: "autumn", translation: "осень" },
  { word: "winter", translation: "зима" },
  { word: "Monday", translation: "понедельник" },
  { word: "Tuesday", translation: "вторник" },
  { word: "Wednesday", translation: "среда" },
  { word: "Thursday", translation: "четверг" },
  { word: "Friday", translation: "пятница" },
  { word: "Saturday", translation: "суббота" },
  { word: "Sunday", translation: "воскресенье" },
  { word: "January", translation: "январь" },
  { word: "February", translation: "февраль" },
  { word: "March", translation: "март" },
  { word: "April", translation: "апрель" },
  { word: "May", translation: "май" },
  { word: "June", translation: "июнь" },
  { word: "July", translation: "июль" },
  { word: "August", translation: "август" },
  { word: "September", translation: "сентябрь" },
  { word: "October", translation: "октябрь" },
  { word: "November", translation: "ноябрь" },
  { word: "December", translation: "декабрь" },
  { word: "very", translation: "очень" },
  { word: "quite", translation: "довольно" },
  { word: "really", translation: "действительно, очень" },
  { word: "too", translation: "тоже; слишком" },
  { word: "also", translation: "тоже, также" },
  { word: "just", translation: "только что; просто" },
  { word: "only", translation: "только" },
  { word: "even", translation: "даже" },
  { word: "far", translation: "далеко" },
  { word: "almost", translation: "почти" },
  { word: "nearly", translation: "почти" },
  { word: "quickly", translation: "быстро" },
  { word: "slowly", translation: "медленно" },
  { word: "carefully", translation: "осторожно" },
  { word: "easily", translation: "легко" },
  { word: "hardly", translation: "едва" },
  { word: "suddenly", translation: "вдруг" },
  { word: "finally", translation: "наконец" },
  { word: "actually", translation: "на самом деле" },
  { word: "probably", translation: "вероятно" },
  { word: "maybe", translation: "может быть" },
  { word: "perhaps", translation: "возможно" },
  { word: "certainly", translation: "конечно, определённо" },
  { word: "clearly", translation: "ясно, чётко" },
  { word: "exactly", translation: "точно" },
  { word: "especially", translation: "особенно" },
  { word: "mostly", translation: "в основном" },
  { word: "completely", translation: "полностью" },
  { word: "totally", translation: "полностью, совершенно" },
  { word: "absolutely", translation: "абсолютно" },
  { word: "simply", translation: "просто" },
  { word: "basically", translation: "в основном, по сути" },
  { word: "generally", translation: "обычно, в общем" },
  { word: "particularly", translation: "особенно" },
  { word: "recently", translation: "недавно" },
  { word: "immediately", translation: "немедленно" },
  { word: "directly", translation: "прямо" },
  { word: "together", translation: "вместе" },
  { word: "apart", translation: "отдельно, врозь" },
  { word: "alone", translation: "один, в одиночестве" },
  { word: "forward", translation: "вперёд" },
  { word: "backward", translation: "назад" },
  { word: "upward", translation: "вверх" },
  { word: "downward", translation: "вниз" },
  { word: "indoors", translation: "внутри помещения" },
  { word: "outdoors", translation: "на улице, вне помещения" },
  { word: "nowhere", translation: "нигде, никуда" },
  { word: "everywhere", translation: "везде" },
  { word: "somewhere", translation: "где-то" },
  { word: "anywhere", translation: "где-нибудь" },
  { word: "person", translation: "человек" },
  { word: "people", translation: "люди" },
  { word: "man", translation: "мужчина" },
  { word: "woman", translation: "женщина" },
  { word: "child", translation: "ребёнок" },
  { word: "children", translation: "дети" },
  { word: "baby", translation: "младенец" },
  { word: "boy", translation: "мальчик" },
  { word: "girl", translation: "девочка" },
  { word: "family", translation: "семья" },
  { word: "parent", translation: "родитель" },
  { word: "mother", translation: "мать" },
  { word: "father", translation: "отец" },
  { word: "mom", translation: "мама" },
  { word: "dad", translation: "папа" },
  { word: "son", translation: "сын" },
  { word: "daughter", translation: "дочь" },
  { word: "brother", translation: "брат" },
  { word: "sister", translation: "сестра" },
  { word: "grandmother", translation: "бабушка" },
  { word: "grandfather", translation: "дедушка" },
  { word: "grandparent", translation: "дедушка/бабушка" },
  { word: "aunt", translation: "тётя" },
  { word: "uncle", translation: "дядя" },
  { word: "cousin", translation: "двоюродный брат/сестра" },
  { word: "nephew", translation: "племянник" },
  { word: "niece", translation: "племянница" },
  { word: "husband", translation: "муж" },
  { word: "wife", translation: "жена" },
  { word: "friend", translation: "друг" },
  { word: "neighbor", translation: "сосед" },
  { word: "teacher", translation: "учитель" },
  { word: "student", translation: "студент, ученик" },
  { word: "doctor", translation: "врач" },
  { word: "nurse", translation: "медсестра" },
  { word: "engineer", translation: "инженер" },
  { word: "lawyer", translation: "юрист" },
  { word: "driver", translation: "водитель" },
  { word: "farmer", translation: "фермер" },
  { word: "waiter", translation: "официант" },
  { word: "police officer", translation: "полицейский" },
  { word: "soldier", translation: "солдат" },
  { word: "artist", translation: "художник" },
  { word: "writer", translation: "писатель" },
  { word: "singer", translation: "певец" },
  { word: "actor", translation: "актёр" },
  { word: "scientist", translation: "учёный" },
  { word: "manager", translation: "менеджер" },
  { word: "worker", translation: "рабочий" },
  { word: "boss", translation: "начальник" },
  { word: "customer", translation: "клиент, покупатель" },
  { word: "guest", translation: "гость" },
  { word: "stranger", translation: "незнакомец" },
  { word: "adult", translation: "взрослый" },
  { word: "teenager", translation: "подросток" },
  { word: "elderly", translation: "пожилой" },
  { word: "body", translation: "тело" },
  { word: "head", translation: "голова" },
  { word: "face", translation: "лицо" },
  { word: "hair", translation: "волосы" },
  { word: "eye", translation: "глаз" },
  { word: "ear", translation: "ухо" },
  { word: "nose", translation: "нос" },
  { word: "mouth", translation: "рот" },
  { word: "tooth", translation: "зуб" },
  { word: "tongue", translation: "язык (орган)" },
  { word: "neck", translation: "шея" },
  { word: "shoulder", translation: "плечо" },
  { word: "arm", translation: "рука (от плеча до кисти)" },
  { word: "elbow", translation: "локоть" },
  { word: "hand", translation: "кисть руки" },
  { word: "finger", translation: "палец (на руке)" },
  { word: "thumb", translation: "большой палец" },
  { word: "chest", translation: "грудь" },
  { word: "back", translation: "спина" },
  { word: "stomach", translation: "живот" },
  { word: "leg", translation: "нога" },
  { word: "knee", translation: "колено" },
  { word: "foot", translation: "ступня" },
  { word: "feet", translation: "ступни" },
  { word: "toe", translation: "палец (на ноге)" },
  { word: "skin", translation: "кожа" },
  { word: "heart", translation: "сердце" },
  { word: "blood", translation: "кровь" },
  { word: "brain", translation: "мозг" },
  { word: "bone", translation: "кость" },
  { word: "muscle", translation: "мышца" },
  { word: "voice", translation: "голос" },
  { word: "food", translation: "еда" },
  { word: "water", translation: "вода" },
  { word: "milk", translation: "молоко" },
  { word: "juice", translation: "сок" },
  { word: "coffee", translation: "кофе" },
  { word: "tea", translation: "чай" },
  { word: "bread", translation: "хлеб" },
  { word: "butter", translation: "масло (сливочное)" },
  { word: "cheese", translation: "сыр" },
  { word: "egg", translation: "яйцо" },
  { word: "meat", translation: "мясо" },
  { word: "chicken", translation: "курица" },
  { word: "beef", translation: "говядина" },
  { word: "fish", translation: "рыба" },
  { word: "rice", translation: "рис" },
  { word: "pasta", translation: "паста, макароны" },
  { word: "soup", translation: "суп" },
  { word: "salad", translation: "салат" },
  { word: "fruit", translation: "фрукт" },
  { word: "vegetable", translation: "овощ" },
  { word: "apple", translation: "яблоко" },
  { word: "banana", translation: "банан" },
  { word: "orange", translation: "апельсин; оранжевый" },
  { word: "potato", translation: "картофель" },
  { word: "tomato", translation: "помидор" },
  { word: "onion", translation: "лук" },
  { word: "carrot", translation: "морковь" },
  { word: "sugar", translation: "сахар" },
  { word: "salt", translation: "соль" },
  { word: "pepper", translation: "перец" },
  { word: "oil", translation: "масло (растительное)" },
  { word: "cake", translation: "торт" },
  { word: "cookie", translation: "печенье" },
  { word: "chocolate", translation: "шоколад" },
  { word: "candy", translation: "конфета" },
  { word: "ice cream", translation: "мороженое" },
  { word: "breakfast", translation: "завтрак" },
  { word: "lunch", translation: "обед" },
  { word: "dinner", translation: "ужин" },
  { word: "snack", translation: "перекус" },
  { word: "meal", translation: "приём пищи" },
  { word: "restaurant", translation: "ресторан" },
  { word: "menu", translation: "меню" },
  { word: "recipe", translation: "рецепт" },
  { word: "taste", translation: "вкус" },
  { word: "hungry", translation: "голодный" },
  { word: "house", translation: "дом" },
  { word: "home", translation: "дом (родной)" },
  { word: "apartment", translation: "квартира" },
  { word: "room", translation: "комната" },
  { word: "kitchen", translation: "кухня" },
  { word: "bedroom", translation: "спальня" },
  { word: "bathroom", translation: "ванная комната" },
  { word: "living room", translation: "гостиная" },
  { word: "garden", translation: "сад" },
  { word: "door", translation: "дверь" },
  { word: "window", translation: "окно" },
  { word: "wall", translation: "стена" },
  { word: "floor", translation: "пол, этаж" },
  { word: "roof", translation: "крыша" },
  { word: "stairs", translation: "лестница" },
  { word: "table", translation: "стол" },
  { word: "chair", translation: "стул" },
  { word: "sofa", translation: "диван" },
  { word: "bed", translation: "кровать" },
  { word: "shelf", translation: "полка" },
  { word: "closet", translation: "шкаф, гардероб" },
  { word: "mirror", translation: "зеркало" },
  { word: "lamp", translation: "лампа" },
  { word: "clock", translation: "часы (настенные)" },
  { word: "key", translation: "ключ" },
  { word: "curtain", translation: "занавеска" },
  { word: "carpet", translation: "ковёр" },
  { word: "blanket", translation: "одеяло" },
  { word: "pillow", translation: "подушка" },
  { word: "towel", translation: "полотенце" },
  { word: "soap", translation: "мыло" },
  { word: "clothes", translation: "одежда" },
  { word: "shirt", translation: "рубашка" },
  { word: "t-shirt", translation: "футболка" },
  { word: "pants", translation: "брюки" },
  { word: "jeans", translation: "джинсы" },
  { word: "dress", translation: "платье" },
  { word: "skirt", translation: "юбка" },
  { word: "jacket", translation: "куртка" },
  { word: "coat", translation: "пальто" },
  { word: "sweater", translation: "свитер" },
  { word: "shoes", translation: "обувь" },
  { word: "boots", translation: "ботинки" },
  { word: "socks", translation: "носки" },
  { word: "hat", translation: "шляпа" },
  { word: "glove", translation: "перчатка" },
  { word: "scarf", translation: "шарф" },
  { word: "belt", translation: "ремень" },
  { word: "bag", translation: "сумка" },
  { word: "wallet", translation: "кошелёк" },
  { word: "glasses", translation: "очки" },
  { word: "ring", translation: "кольцо" },
  { word: "necklace", translation: "ожерелье" },
  { word: "nature", translation: "природа" },
  { word: "weather", translation: "погода" },
  { word: "sun", translation: "солнце" },
  { word: "moon", translation: "луна" },
  { word: "star", translation: "звезда" },
  { word: "sky", translation: "небо" },
  { word: "cloud", translation: "облако" },
  { word: "rain", translation: "дождь" },
  { word: "snow", translation: "снег" },
  { word: "wind", translation: "ветер" },
  { word: "storm", translation: "буря" },
  { word: "fog", translation: "туман" },
  { word: "ice", translation: "лёд" },
  { word: "fire", translation: "огонь; пожар" },
  { word: "earth", translation: "земля" },
  { word: "ground", translation: "земля, почва" },
  { word: "mountain", translation: "гора" },
  { word: "hill", translation: "холм" },
  { word: "river", translation: "река" },
  { word: "lake", translation: "озеро" },
  { word: "sea", translation: "море" },
  { word: "ocean", translation: "океан" },
  { word: "beach", translation: "пляж" },
  { word: "forest", translation: "лес" },
  { word: "tree", translation: "дерево" },
  { word: "flower", translation: "цветок" },
  { word: "grass", translation: "трава" },
  { word: "leaf", translation: "лист" },
  { word: "rock", translation: "камень, скала" },
  { word: "sand", translation: "песок" },
  { word: "island", translation: "остров" },
  { word: "field", translation: "поле" },
  { word: "desert", translation: "пустыня" },
  { word: "valley", translation: "долина" },
  { word: "animal", translation: "животное" },
  { word: "dog", translation: "собака" },
  { word: "cat", translation: "кошка" },
  { word: "bird", translation: "птица" },
  { word: "horse", translation: "лошадь" },
  { word: "cow", translation: "корова" },
  { word: "pig", translation: "свинья" },
  { word: "sheep", translation: "овца" },
  { word: "goat", translation: "коза" },
  { word: "duck", translation: "утка" },
  { word: "rabbit", translation: "кролик" },
  { word: "mouse", translation: "мышь" },
  { word: "lion", translation: "лев" },
  { word: "tiger", translation: "тигр" },
  { word: "bear", translation: "медведь" },
  { word: "elephant", translation: "слон" },
  { word: "monkey", translation: "обезьяна" },
  { word: "wolf", translation: "волк" },
  { word: "fox", translation: "лиса" },
  { word: "deer", translation: "олень" },
  { word: "snake", translation: "змея" },
  { word: "frog", translation: "лягушка" },
  { word: "insect", translation: "насекомое" },
  { word: "bee", translation: "пчела" },
  { word: "butterfly", translation: "бабочка" },
  { word: "spider", translation: "паук" },
  { word: "ant", translation: "муравей" },
  { word: "place", translation: "место" },
  { word: "city", translation: "город" },
  { word: "town", translation: "городок" },
  { word: "village", translation: "деревня" },
  { word: "country", translation: "страна" },
  { word: "street", translation: "улица" },
  { word: "road", translation: "дорога" },
  { word: "building", translation: "здание" },
  { word: "school", translation: "школа" },
  { word: "university", translation: "университет" },
  { word: "hospital", translation: "больница" },
  { word: "church", translation: "церковь" },
  { word: "library", translation: "библиотека" },
  { word: "museum", translation: "музей" },
  { word: "store", translation: "магазин" },
  { word: "shop", translation: "магазин" },
  { word: "market", translation: "рынок" },
  { word: "bank", translation: "банк" },
  { word: "hotel", translation: "отель" },
  { word: "park", translation: "парк" },
  { word: "bridge", translation: "мост" },
  { word: "airport", translation: "аэропорт" },
  { word: "station", translation: "станция, вокзал" },
  { word: "office", translation: "офис" },
  { word: "factory", translation: "фабрика" },
  { word: "farm", translation: "ферма" },
  { word: "zoo", translation: "зоопарк" },
  { word: "car", translation: "машина" },
  { word: "bus", translation: "автобус" },
  { word: "plane", translation: "самолёт" },
  { word: "bike", translation: "велосипед" },
  { word: "motorcycle", translation: "мотоцикл" },
  { word: "boat", translation: "лодка" },
  { word: "ship", translation: "корабль" },
  { word: "taxi", translation: "такси" },
  { word: "truck", translation: "грузовик" },
  { word: "subway", translation: "метро" },
  { word: "ticket", translation: "билет" },
  { word: "traffic", translation: "дорожное движение" },
  { word: "engine", translation: "двигатель" },
  { word: "wheel", translation: "колесо" },
  { word: "fuel", translation: "топливо" },
  { word: "job", translation: "работа" },
  { word: "career", translation: "карьера" },
  { word: "company", translation: "компания" },
  { word: "business", translation: "бизнес" },
  { word: "meeting", translation: "встреча, совещание" },
  { word: "project", translation: "проект" },
  { word: "task", translation: "задача" },
  { word: "report", translation: "отчёт" },
  { word: "salary", translation: "зарплата" },
  { word: "interview", translation: "собеседование" },
  { word: "resume", translation: "резюме" },
  { word: "colleague", translation: "коллега" },
  { word: "client", translation: "клиент" },
  { word: "deadline", translation: "крайний срок" },
  { word: "schedule", translation: "расписание" },
  { word: "class", translation: "урок, класс" },
  { word: "lesson", translation: "урок" },
  { word: "homework", translation: "домашнее задание" },
  { word: "exam", translation: "экзамен" },
  { word: "test", translation: "тест" },
  { word: "grade", translation: "оценка" },
  { word: "subject", translation: "предмет (учебный)" },
  { word: "book", translation: "книга" },
  { word: "notebook", translation: "тетрадь" },
  { word: "pen", translation: "ручка" },
  { word: "pencil", translation: "карандаш" },
  { word: "paper", translation: "бумага" },
  { word: "page", translation: "страница" },
  { word: "desk", translation: "письменный стол" },
  { word: "board", translation: "доска" },
  { word: "lecture", translation: "лекция" },
  { word: "degree", translation: "степень (учёная)" },
  { word: "knowledge", translation: "знание" },
  { word: "skill", translation: "навык" },
  { word: "experience", translation: "опыт" },
  { word: "computer", translation: "компьютер" },
  { word: "phone", translation: "телефон" },
  { word: "internet", translation: "интернет" },
  { word: "email", translation: "электронная почта" },
  { word: "message", translation: "сообщение" },
  { word: "website", translation: "веб-сайт" },
  { word: "screen", translation: "экран" },
  { word: "keyboard", translation: "клавиатура" },
  { word: "password", translation: "пароль" },
  { word: "file", translation: "файл" },
  { word: "software", translation: "программное обеспечение" },
  { word: "camera", translation: "камера" },
  { word: "photo", translation: "фото" },
  { word: "video", translation: "видео" },
  { word: "music", translation: "музыка" },
  { word: "game", translation: "игра" },
  { word: "television", translation: "телевизор" },
  { word: "radio", translation: "радио" },
  { word: "network", translation: "сеть" },
  { word: "battery", translation: "батарея" },
  { word: "charger", translation: "зарядное устройство" },
  { word: "app", translation: "приложение" },
  { word: "data", translation: "данные" },
  { word: "signal", translation: "сигнал" },
  { word: "love", translation: "любовь" },
  { word: "hate", translation: "ненависть" },
  { word: "fear", translation: "страх" },
  { word: "hope", translation: "надежда" },
  { word: "joy", translation: "радость" },
  { word: "anger", translation: "гнев" },
  { word: "surprise", translation: "удивление" },
  { word: "peace", translation: "мир, покой" },
  { word: "freedom", translation: "свобода" },
  { word: "truth", translation: "правда" },
  { word: "lie", translation: "ложь" },
  { word: "idea", translation: "идея" },
  { word: "opinion", translation: "мнение" },
  { word: "fact", translation: "факт" },
  { word: "reason", translation: "причина" },
  { word: "problem", translation: "проблема" },
  { word: "solution", translation: "решение" },
  { word: "question", translation: "вопрос" },
  { word: "answer", translation: "ответ" },
  { word: "decision", translation: "решение (выбор)" },
  { word: "choice", translation: "выбор" },
  { word: "chance", translation: "шанс" },
  { word: "risk", translation: "риск" },
  { word: "success", translation: "успех" },
  { word: "failure", translation: "неудача" },
  { word: "effort", translation: "усилие" },
  { word: "goal", translation: "цель" },
  { word: "dream", translation: "мечта" },
  { word: "memory", translation: "память, воспоминание" },
  { word: "mind", translation: "разум" },
  { word: "thought", translation: "мысль" },
  { word: "feeling", translation: "чувство" },
  { word: "mood", translation: "настроение" },
  { word: "attitude", translation: "отношение, позиция" },
  { word: "value", translation: "ценность" },
  { word: "belief", translation: "убеждение, вера" },
  { word: "culture", translation: "культура" },
  { word: "society", translation: "общество" },
  { word: "community", translation: "сообщество" },
  { word: "relationship", translation: "отношения" },
  { word: "friendship", translation: "дружба" },
  { word: "marriage", translation: "брак" },
  { word: "color", translation: "цвет" },
  { word: "red", translation: "красный" },
  { word: "blue", translation: "синий" },
  { word: "green", translation: "зелёный" },
  { word: "yellow", translation: "жёлтый" },
  { word: "black", translation: "чёрный" },
  { word: "white", translation: "белый" },
  { word: "gray", translation: "серый" },
  { word: "brown", translation: "коричневый" },
  { word: "pink", translation: "розовый" },
  { word: "purple", translation: "фиолетовый" },
  { word: "money", translation: "деньги" },
  { word: "price", translation: "цена" },
  { word: "cost", translation: "стоимость" },
  { word: "cash", translation: "наличные" },
  { word: "coin", translation: "монета" },
  { word: "bill", translation: "счёт, купюра" },
  { word: "credit card", translation: "кредитная карта" },
  { word: "discount", translation: "скидка" },
  { word: "sale", translation: "распродажа" },
  { word: "shopping", translation: "покупки" },
  { word: "receipt", translation: "чек" },
  { word: "budget", translation: "бюджет" },
  { word: "debt", translation: "долг" },
  { word: "profit", translation: "прибыль" },
  { word: "tax", translation: "налог" },
  { word: "insurance", translation: "страховка" },
  { word: "loan", translation: "кредит, займ" },
  { word: "health", translation: "здоровье" },
  { word: "medicine", translation: "лекарство" },
  { word: "pain", translation: "боль" },
  { word: "disease", translation: "болезнь" },
  { word: "injury", translation: "травма" },
  { word: "treatment", translation: "лечение" },
  { word: "surgery", translation: "операция (хирургическая)" },
  { word: "symptom", translation: "симптом" },
  { word: "fever", translation: "температура (жар)" },
  { word: "cough", translation: "кашель" },
  { word: "headache", translation: "головная боль" },
  { word: "diet", translation: "диета" },
  { word: "vitamin", translation: "витамин" },
  { word: "sport", translation: "спорт" },
  { word: "team", translation: "команда" },
  { word: "ball", translation: "мяч" },
  { word: "match", translation: "матч" },
  { word: "race", translation: "гонка, забег" },
  { word: "gym", translation: "спортзал" },
  { word: "swimming", translation: "плавание" },
  { word: "football", translation: "футбол" },
  { word: "basketball", translation: "баскетбол" },
  { word: "tennis", translation: "теннис" },
  { word: "hobby", translation: "хобби" },
  { word: "art", translation: "искусство" },
  { word: "painting", translation: "картина" },
  { word: "photography", translation: "фотография" },
  { word: "reading", translation: "чтение" },
  { word: "travel", translation: "путешествие" },
  { word: "vacation", translation: "отпуск, каникулы" },
  { word: "thing", translation: "вещь" },
  { word: "stuff", translation: "вещи, барахло" },
  { word: "object", translation: "объект, предмет" },
  { word: "item", translation: "предмет, пункт" },
  { word: "box", translation: "коробка" },
  { word: "container", translation: "контейнер" },
  { word: "package", translation: "посылка, упаковка" },
  { word: "letter", translation: "письмо, буква" },
  { word: "note", translation: "записка, заметка" },
  { word: "list", translation: "список" },
  { word: "map", translation: "карта" },
  { word: "sign", translation: "знак" },
  { word: "symbol", translation: "символ" },
  { word: "number", translation: "число, номер" },
  { word: "amount", translation: "количество" },
  { word: "level", translation: "уровень" },
  { word: "size", translation: "размер" },
  { word: "shape", translation: "форма" },
  { word: "line", translation: "линия" },
  { word: "area", translation: "область, площадь" },
  { word: "space", translation: "пространство; космос" },
  { word: "distance", translation: "расстояние" },
  { word: "direction", translation: "направление" },
  { word: "side", translation: "сторона" },
  { word: "top", translation: "верх" },
  { word: "bottom", translation: "низ" },
  { word: "middle", translation: "середина" },
  { word: "corner", translation: "угол" },
  { word: "left", translation: "левый; налево" },
  { word: "front", translation: "перёд, фасад" },
  { word: "center", translation: "центр" },
  { word: "edge", translation: "край" },
  { word: "surface", translation: "поверхность" },
  { word: "part", translation: "часть" },
  { word: "piece", translation: "кусок, часть" },
  { word: "half", translation: "половина" },
  { word: "quarter", translation: "четверть" },
  { word: "group", translation: "группа" },
  { word: "system", translation: "система" },
  { word: "process", translation: "процесс" },
  { word: "method", translation: "метод" },
  { word: "law", translation: "закон" },
  { word: "right", translation: "право; правый" },
  { word: "power", translation: "сила, власть" },
  { word: "energy", translation: "энергия" },
  { word: "force", translation: "сила" },
  { word: "speed", translation: "скорость" },
  { word: "quality", translation: "качество" },
  { word: "quantity", translation: "количество" },
  { word: "condition", translation: "условие, состояние" },
  { word: "situation", translation: "ситуация" },
  { word: "event", translation: "событие" },
  { word: "history", translation: "история" },
  { word: "future", translation: "будущее" },
  { word: "past", translation: "прошлое" },
  { word: "present", translation: "настоящее (время); подарок" },
  { word: "life", translation: "жизнь" },
  { word: "death", translation: "смерть" },
  { word: "name", translation: "имя" },
  { word: "world", translation: "мир" },
  { word: "universe", translation: "вселенная" },
  { word: "government", translation: "правительство" },
  { word: "president", translation: "президент" },
  { word: "war", translation: "война" },
  { word: "army", translation: "армия" },
  { word: "religion", translation: "религия" },
  { word: "god", translation: "бог" },
  { word: "language", translation: "язык (речь)" },
  { word: "word", translation: "слово" },
  { word: "sentence", translation: "предложение (грамм.)" },
  { word: "meaning", translation: "значение" },
  { word: "noise", translation: "шум" },
  { word: "silence", translation: "тишина" },
  { word: "smell", translation: "запах" },
  { word: "shadow", translation: "тень" },
  { word: "reflection", translation: "отражение" },
  { word: "temperature", translation: "температура" },
  { word: "gas", translation: "газ" },
  { word: "metal", translation: "металл" },
  { word: "wood", translation: "дерево (материал)" },
  { word: "glass", translation: "стекло" },
  { word: "plastic", translation: "пластик" },
  { word: "cotton", translation: "хлопок" },
  { word: "material", translation: "материал" },
  { word: "product", translation: "продукт" },
  { word: "service", translation: "услуга" },
  { word: "brand", translation: "бренд" },
  { word: "advertisement", translation: "реклама" },
  { word: "industry", translation: "промышленность" },
  { word: "agriculture", translation: "сельское хозяйство" },
  { word: "environment", translation: "окружающая среда" },
  { word: "pollution", translation: "загрязнение" },
  { word: "climate", translation: "климат" },
  { word: "planet", translation: "планета" },
  { word: "technology", translation: "технология" },
  { word: "science", translation: "наука" },
  { word: "mathematics", translation: "математика" },
  { word: "chemistry", translation: "химия" },
  { word: "physics", translation: "физика" },
  { word: "biology", translation: "биология" },
  { word: "geography", translation: "география" },
  { word: "literature", translation: "литература" },
  { word: "philosophy", translation: "философия" },
  { word: "economy", translation: "экономика" },
  { word: "politics", translation: "политика" },
  { word: "election", translation: "выборы" },
  { word: "vote", translation: "голосовать; голос" },
  { word: "crime", translation: "преступление" },
  { word: "justice", translation: "справедливость" },
  { word: "prison", translation: "тюрьма" },
  { word: "court", translation: "суд" },
  { word: "judge", translation: "судья" },
  { word: "jury", translation: "присяжные" },
  { word: "witness", translation: "свидетель" },
  { word: "victim", translation: "жертва" },
  { word: "danger", translation: "опасность" },
  { word: "accident", translation: "несчастный случай, авария" },
  { word: "emergency", translation: "чрезвычайная ситуация" },
  { word: "disaster", translation: "катастрофа" },
  { word: "earthquake", translation: "землетрясение" },
  { word: "flood", translation: "наводнение" },
  { word: "like", translation: "нравиться; как, подобно" },
  { word: "light", translation: "свет; лёгкий (по весу); светлый" },
  { word: "end", translation: "заканчивать(ся); конец" },
  { word: "wrong", translation: "неправильный" },
  { word: "finish", translation: "заканчивать, финишировать" },
  { word: "wish", translation: "желать; желание" },
  { word: "free", translation: "свободный, бесплатный" },
  { word: "sound", translation: "звук; звучать" },
  { word: "plan", translation: "планировать; план" },
  { word: "same", translation: "тот же самый" },
  { word: "point", translation: "указывать; точка" },
  { word: "type", translation: "печатать (на клавиатуре); тип" },
  { word: "sure", translation: "уверенный" },
  { word: "train", translation: "тренировать(ся), поезд" },
  { word: "order", translation: "заказывать, приказывать; порядок" },
  { word: "strong", translation: "сильный" },
  { word: "matter", translation: "иметь значение; вопрос, дело" },
  { word: "deal", translation: "иметь дело, сделка" },
  { word: "weak", translation: "слабый" },
  { word: "stick", translation: "приклеивать, палка" },
  { word: "stay", translation: "оставаться" },
  { word: "rich", translation: "богатый" },
  { word: "open", translation: "открывать" },
  { word: "say", translation: "говорить, сказать" },
  { word: "poor", translation: "бедный" },
  { word: "get", translation: "получать, становиться" },
  { word: "make", translation: "делать, создавать" },
  { word: "beautiful", translation: "красивый" },
  { word: "go", translation: "идти, ехать" },
  { word: "know", translation: "знать" },
  { word: "clear", translation: "ясный, понятный; чистый" },
  { word: "take", translation: "брать" },
  { word: "see", translation: "видеть" },
  { word: "close", translation: "близкий; закрывать" },
  { word: "come", translation: "приходить" },
  { word: "think", translation: "думать" },
  { word: "fast", translation: "быстрый" },
  { word: "look", translation: "смотреть" },
  { word: "want", translation: "хотеть" },
  { word: "slow", translation: "медленный" },
  { word: "give", translation: "давать" },
  { word: "happy", translation: "счастливый" },
  { word: "use", translation: "использовать" },
  { word: "find", translation: "находить" },
  { word: "sad", translation: "грустный" },
  { word: "tell", translation: "рассказывать, говорить" },
  { word: "ask", translation: "спрашивать, просить" },
  { word: "angry", translation: "злой, сердитый" },
  { word: "work", translation: "работать" },
  { word: "seem", translation: "казаться" },
  { word: "tired", translation: "уставший" },
  { word: "feel", translation: "чувствовать" },
  { word: "try", translation: "пытаться" },
  { word: "thirsty", translation: "испытывающий жажду" },
  { word: "leave", translation: "уходить, оставлять" },
  { word: "call", translation: "звать, звонить" },
  { word: "easy", translation: "лёгкий (несложный)" },
  { word: "need", translation: "нуждаться" },
  { word: "become", translation: "становиться" },
  { word: "hard", translation: "твёрдый, трудный" },
  { word: "put", translation: "класть, ставить" },
  { word: "mean", translation: "означать, иметь в виду" },
  { word: "dirty", translation: "грязный" },
  { word: "keep", translation: "хранить, продолжать" },
  { word: "let", translation: "позволять" },
  { word: "clean", translation: "чистый" },
  { word: "begin", translation: "начинать" },
  { word: "help", translation: "помогать" },
  { word: "hot", translation: "горячий, жаркий" },
  { word: "talk", translation: "разговаривать" },
  { word: "turn", translation: "поворачивать(ся)" },
  { word: "cold", translation: "холодный" },
  { word: "start", translation: "начинать" },
  { word: "show", translation: "показывать" },
  { word: "warm", translation: "тёплый" },
  { word: "hear", translation: "слышать" },
  { word: "play", translation: "играть" },
  { word: "cool", translation: "прохладный" },
  { word: "run", translation: "бежать" },
  { word: "move", translation: "двигаться, переезжать" },
  { word: "good", translation: "хороший" },
  { word: "live", translation: "жить" },
  { word: "bad", translation: "плохой" },
  { word: "believe", translation: "верить" },
  { word: "bring", translation: "приносить" },
  { word: "big", translation: "большой" },
  { word: "happen", translation: "случаться" },
  { word: "write", translation: "писать" },
  { word: "small", translation: "маленький" },
  { word: "provide", translation: "предоставлять" },
  { word: "sit", translation: "сидеть" },
  { word: "large", translation: "большой, крупный" },
  { word: "stand", translation: "стоять" },
  { word: "lose", translation: "терять, проигрывать" },
  { word: "new", translation: "новый" },
  { word: "pay", translation: "платить" },
  { word: "meet", translation: "встречать(ся)" },
  { word: "old", translation: "старый" },
  { word: "include", translation: "включать" },
  { word: "continue", translation: "продолжать" },
  { word: "young", translation: "молодой" },
  { word: "set", translation: "устанавливать, ставить" },
  { word: "learn", translation: "учиться, узнавать" },
  { word: "high", translation: "высокий" },
  { word: "change", translation: "менять(ся)" },
  { word: "lead", translation: "вести, руководить" },
  { word: "low", translation: "низкий" },
  { word: "understand", translation: "понимать" },
  { word: "watch", translation: "смотреть, наблюдать; наручные часы" },
  { word: "long", translation: "длинный" },
  { word: "follow", translation: "следовать" },
  { word: "stop", translation: "останавливать(ся)" },
  { word: "short", translation: "короткий" },
]
